cat 3_2_CLASSIFIER_DATA/THERMO_SPLITTING/train_all_fasta_$1 3_2_CLASSIFIER_DATA/MESO_DATA/MESO_TRAIN_$1 >  3_2_CLASSIFIER_DATA/TRAIN_cl_$1

awk  -i inplace '!visited[$0]++'  3_2_CLASSIFIER_DATA/TRAIN_cl_$1




cat 3_2_CLASSIFIER_DATA/THERMO_SPLITTING/test_all_fasta_$1 3_2_CLASSIFIER_DATA/MESO_DATA/MESO_TEST_$1 > 3_2_CLASSIFIER_DATA/TEST_cl_$1

awk -i inplace '!visited[$0]++'  3_2_CLASSIFIER_DATA/TEST_cl_$1




cat 3_2_CLASSIFIER_DATA/THERMO_SPLITTING/val_all_fasta_$1 3_2_CLASSIFIER_DATA/MESO_DATA/MESO_VAL_$1 > 3_2_CLASSIFIER_DATA/VAL_cl_$1

awk -i inplace '!visited[$0]++'  3_2_CLASSIFIER_DATA/VAL_cl_$1




